import Head from "next/head";
import Image from "next/image";
import { Navbar, NavContent, Footer } from "..";

import { faAngleRight } from "@fortawesome/free-solid-svg-icons";

type LayoutProps = {
  title: string;
  h1: string;
  children: React.ReactNode;
};

const navContents: NavContent[] = [
  { id: 1, content: "Our trips", href: "/", rightIcon: faAngleRight },
  { id: 2, content: "Create a trip", href: "/post", rightIcon: faAngleRight },
  { id: 3, content: "Why Fresh Tracks", href: "/" },
];

/**
 * Additional Docs
 */
export const Layout = ({ title, h1, children }: LayoutProps) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-secondary min-h-screen">
        <Navbar navContents={navContents} />
        <div className="px-12">
          <div className="py-8 text-center">
            <h1 className="text-3xl font-bold underline uppercase">{h1}</h1>
          </div>
          {children}
        </div>
      </main>

      <Footer />
    </div>
  );
};
