import Head from "next/head";
import Image from "next/image";

type LayoutProps = {
  title: string;
  h1: string;
  children: React.ReactNode;
};

/**
 * Additional Docs
 */
export const Layout = ({ title, h1, children }: LayoutProps) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white bg-slate-800 min-h-screen">
        <div className="py-8 text-center">
          <h1 className="text-3xl font-bold underline uppercase">{h1}</h1>
        </div>
        {children}
      </main>

      <footer className="py-4 bg-slate-700 text-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
