// @ts-nocheck
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { request } from "../lib/datocms";

const HOMEPAGE_QUERY = `
query HomePage {
  allArticles {
    title
    id
    createdAt
    content
  }
}`;
export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY,
  });
  return {
    props: { data },
  };
}

const Home: NextPage = ({ data }) => {
  console.log(data.allArticles);
  return (
    <div className={styles.container}>
      <Head>
        <title>JamStack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>JamStack</h1>
        {data.allArticles.map((article) => (
          <div key={article.title}>
            <h5>{article.title}</h5>
            <p>{article.content}</p>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
